version: '3'

networks:
  clientnet:
    driver: bridge

services:
  client_web:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: client_web
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    networks:
     - clientnet
  client_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: client_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: langschool
    volumes:
     - ./data/conf:/etc/mysql/conf.d
     - ./data/db:/var/lib/mysql
    ports:
     - 127.0.0.1:3306:3306
    networks:
     - clientnet